import { join } from 'node:path'
import type { NewsFeedSource, NoveltyProfile } from './types'

export type AppConfig = {
  port: number
  hostname: string
  dataDir: string
  dbPath: string
  distDir: string
  dataRefreshMs: number
  fetchTimeoutMs: number
  popularRefreshMs: number
  popularEnsureMs: number
  popularRetentionMs: number
  portfolioRefreshMs: number
  portfolioQuantReoptimizeMs: number
  portfolioNoveltyProfile: NoveltyProfile
  portfolioDiversityWeight: number
  optimizeExecutor: 'embedded' | 'external'
  watchlist: string[]
  newsFeedSources: NewsFeedSource[]
}

/** Default universe when `WATCHLIST_SYMBOLS` is unset; also seeds the built-in Default portfolio scenario. */
export const defaultWatchlist = [
  'SPY',
  'QQQ',
  'DIA',
  'IWM',
  'IVV',
  'VOO',
  'VTI',
  'RSP',
  'MDY',
  'IJR',
  'XLE',
  'XLF',
  'XLK',
  'XLV',
  'XLY',
  'XLP',
  'XLI',
  'XLU',
  'XLB',
  'XLRE',
  'SMH',
  'SOXX',
  'ARKK',
  'TLT',
  'HYG',
  'GLD',
  'SLV',
  'USO',
  'AAPL',
  'MSFT',
  'NVDA',
  'AMD',
  'AVGO',
  'TSLA',
  'META',
  'AMZN',
  'GOOGL',
  'NFLX',
  'ORCL',
  'CRM',
  'ADBE',
  'CSCO',
  'IBM',
  'INTC',
  'QCOM',
  'TXN',
  'MU',
  'MRVL',
  'ADI',
  'AMAT',
  'LRCX',
  'KLAC',
  'ASML',
  'TSM',
  'ARM',
  'SNOW',
  'NOW',
  'PANW',
  'CRWD',
  'NET',
  'DDOG',
  'MDB',
  'PLTR',
  'SHOP',
  'UBER',
  'ABNB',
  'DASH',
  'RBLX',
  'SNAP',
  'PINS',
  'PYPL',
  'SQ',
  'T',
  'VZ',
  'TMUS',
  'CMCSA',
  'CHTR',
  'PARA',
  'WBD',
  'ROKU',
  'SPOT',
  'JPM',
  'BAC',
  'GS',
  'MS',
  'C',
  'WFC',
  'USB',
  'PNC',
  'SCHW',
  'BLK',
  'BX',
  'KKR',
  'V',
  'MA',
  'AXP',
  'COF',
  'DFS',
  'ALL',
  'TRV',
  'CB',
  'AIG',
  'MET',
  'PRU',
  'CME',
  'ICE',
  'MCO',
  'SPGI',
  'UNH',
  'LLY',
  'JNJ',
  'PFE',
  'MRK',
  'ABBV',
  'ABT',
  'TMO',
  'DHR',
  'BMY',
  'AMGN',
  'GILD',
  'REGN',
  'ISRG',
  'MDT',
  'SYK',
  'BSX',
  'ELV',
  'HUM',
  'CVS',
  'CI',
  'MCK',
  'COR',
  'ZTS',
  'HCA',
  'WMT',
  'COST',
  'HD',
  'DIS',
  'PG',
  'KO',
  'PEP',
  'MCD',
  'SBUX',
  'NKE',
  'TGT',
  'LOW',
  'TJX',
  'ROST',
  'BKNG',
  'MAR',
  'HLT',
  'GM',
  'F',
  'RIVN',
  'LCID',
  'ORLY',
  'AZO',
  'CMG',
  'YUM',
  'DPZ',
  'EL',
  'CL',
  'KMB',
  'GIS',
  'K',
  'MDLZ',
  'HSY',
  'KR',
  'BA',
  'CAT',
  'GE',
  'RTX',
  'LMT',
  'NOC',
  'GD',
  'HON',
  'UPS',
  'FDX',
  'DE',
  'MMM',
  'ETN',
  'EMR',
  'ITW',
  'PH',
  'CMI',
  'URI',
  'WM',
  'RSG',
  'NSC',
  'UNP',
  'CSX',
  'DAL',
  'UAL',
  'AAL',
  'LUV',
  'RCL',
  'CCL',
  'NCLH',
  'XOM',
  'CVX',
  'COP',
  'EOG',
  'SLB',
  'HAL',
  'OXY',
  'MPC',
  'VLO',
  'PSX',
  'KMI',
  'WMB',
  'LNG',
  'FANG',
  'DVN',
  'APA',
  'BKR',
  'FCX',
  'NEM',
  'AA',
  'NUE',
  'STLD',
  'DOW',
  'DD',
  'LIN',
  'APD',
  'SHW',
  'ECL',
  'SCCO',
  'AMT',
  'PLD',
  'EQIX',
  'CCI',
  'PSA',
  'O',
  'SPG',
  'DLR',
  'NEE',
  'SO',
  'DUK',
  'AEP',
  'EXC',
  'SRE',
  'PCG',
  'D',
  'PEG',
  'XEL',
  'BABA',
  'JD',
  'PDD',
  'BIDU',
  'NIO',
  'LI',
  'XPEV',
  'SAP',
  'SHEL',
  'BP',
  'TM',
  'SONY',
  'NVO',
  'AZN',
  'RIO',
  'BHP',
  'VALE',
  'MELI',
  'SE',
  'NU',
  'COIN',
  'MSTR',
  'HOOD',
  'IBKR',
  'RIOT',
  'MARA',
  'CLSK',
  'HUT',
  'BITF',
]

export const newsFeedSources: NewsFeedSource[] = [
  {
    name: 'Yahoo Finance RSS',
    url: 'https://feeds.finance.yahoo.com/rss/2.0/headline?s=AAPL,MSFT,NVDA,TSLA,META,AMZN,GOOGL&region=US&lang=en-US',
  },
  { name: 'CNBC Top News RSS', url: 'https://www.cnbc.com/id/100003114/device/rss/rss.html' },
  { name: 'CNBC Markets RSS', url: 'https://www.cnbc.com/id/10001147/device/rss/rss.html' },
  { name: 'MarketWatch Top Stories RSS', url: 'https://feeds.content.dowjones.io/public/rss/mw_topstories' },
  { name: 'Investing.com Economy RSS', url: 'https://www.investing.com/rss/news_1.rss' },
  { name: 'Investing.com Stocks RSS', url: 'https://www.investing.com/rss/news_25.rss' },
  { name: 'Investing.com Commodities RSS', url: 'https://www.investing.com/rss/news_11.rss' },
  { name: 'Investing.com Crypto RSS', url: 'https://www.investing.com/rss/news_301.rss' },
  { name: 'Bloomberg Markets RSS', url: 'https://feeds.bloomberg.com/markets/news.rss' },
  { name: 'Bloomberg Economics RSS', url: 'https://feeds.bloomberg.com/economics/news.rss' },
  { name: 'NYT Business RSS', url: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml' },
  { name: 'NYT Economy RSS', url: 'https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml' },
  { name: 'Dow Jones WSJ Markets RSS', url: 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml' },
  { name: 'BBC Business RSS', url: 'https://feeds.bbci.co.uk/news/business/rss.xml' },
  { name: 'Sky News Business RSS', url: 'https://feeds.skynews.com/feeds/rss/business.xml' },
  { name: 'Guardian Business RSS', url: 'https://www.theguardian.com/uk/business/rss' },
  { name: 'TechCrunch RSS', url: 'https://techcrunch.com/feed/' },
  { name: 'Ars Technica RSS', url: 'https://arstechnica.com/feed/' },
  { name: 'The Verge RSS', url: 'https://www.theverge.com/rss/index.xml' },
  { name: 'MIT Technology Review RSS', url: 'https://www.technologyreview.com/feed/' },
  { name: 'The Register Headlines Atom', url: 'https://www.theregister.com/headlines.atom' },
  { name: 'Semiconductor Engineering RSS', url: 'https://semiengineering.com/feed/' },
  { name: 'CoinDesk RSS', url: 'https://www.coindesk.com/arc/outboundfeeds/rss/' },
  { name: 'Business Insider RSS', url: 'https://www.businessinsider.com/rss' },
  { name: 'Forbes Business RSS', url: 'https://www.forbes.com/business/feed/' },
  { name: 'Fortune RSS', url: 'https://fortune.com/feed/' },
  { name: 'The Economist Finance & Economics RSS', url: 'https://www.economist.com/finance-and-economics/rss.xml' },
  { name: 'EIA Today in Energy RSS', url: 'https://www.eia.gov/rss/todayinenergy.xml' },
  { name: 'OilPrice RSS', url: 'https://oilprice.com/rss/main' },
  { name: 'US Census Economic Indicators RSS', url: 'https://www.census.gov/economic-indicators/indicator.xml' },
  { name: 'Federal Reserve RSS', url: 'https://www.federalreserve.gov/feeds/press_all.xml' },
  { name: 'ECB Press RSS', url: 'https://www.ecb.europa.eu/rss/press.html' },
  { name: 'Bank of England News RSS', url: 'https://www.bankofengland.co.uk/rss/news' },
  { name: 'SEC Press Releases RSS', url: 'https://www.sec.gov/news/pressreleases.rss' },
]

const secondsToMs = (seconds: number) => seconds * 1000
const minutesToMs = (minutes: number) => secondsToMs(minutes * 60)
const daysToMs = (days: number) => minutesToMs(days * 24 * 60)
const getEnvNumber = (name: string, fallback: number, options: { min?: number; max?: number } = {}) => {
  const parsed = Number(Bun.env[name] ?? fallback)
  if (!Number.isFinite(parsed)) return fallback
  const min = options.min ?? Number.NEGATIVE_INFINITY
  const max = options.max ?? Number.POSITIVE_INFINITY
  return Math.min(max, Math.max(min, parsed))
}
const getNoveltyProfile = (value: string | undefined): NoveltyProfile =>
  value === 'low' || value === 'high' || value === 'medium' ? value : 'medium'

const getOptimizeExecutor = (value: string | undefined): 'embedded' | 'external' => (value === 'external' ? 'external' : 'embedded')

const assertHttpsFeedSources = (feeds: NewsFeedSource[]) => {
  for (const feed of feeds) {
    if (!feed.url.startsWith('https://')) {
      throw new Error(`News feed "${feed.name}" must use an https:// URL (got ${feed.url})`)
    }
  }
}

export const createConfig = (): AppConfig => {
  assertHttpsFeedSources(newsFeedSources)
  const dataDir = Bun.env.DATA_DIR ?? join(process.cwd(), 'data')
  const watchlistRaw = Bun.env.WATCHLIST_SYMBOLS?.trim() ? Bun.env.WATCHLIST_SYMBOLS : defaultWatchlist.join(',')

  return {
    port: Math.floor(getEnvNumber('API_PORT', 3210, { min: 1, max: 65_535 })),
    hostname: Bun.env.HOST ?? '0.0.0.0',
    dataDir,
    dbPath: Bun.env.SQLITE_PATH ?? join(dataDir, 'boomboom.sqlite'),
    distDir: join(process.cwd(), 'dist'),
    dataRefreshMs: secondsToMs(getEnvNumber('DATA_REFRESH_SECONDS', 600, { min: 1 })),
    fetchTimeoutMs: secondsToMs(getEnvNumber('OPEN_DATA_TIMEOUT_SECONDS', 8, { min: 1 })),
    popularRefreshMs: minutesToMs(getEnvNumber('POPULAR_REFRESH_MINUTES', 15, { min: 1 })),
    popularEnsureMs: minutesToMs(getEnvNumber('POPULAR_ENSURE_MINUTES', 15, { min: 1 })),
    popularRetentionMs: daysToMs(getEnvNumber('POPULAR_RETENTION_DAYS', 30, { min: 1 })),
    portfolioRefreshMs: minutesToMs(getEnvNumber('PORTFOLIO_REFRESH_MINUTES', 10, { min: 1 })),
    portfolioQuantReoptimizeMs: minutesToMs(getEnvNumber('PORTFOLIO_QUANT_REOPTIMIZE_MINUTES', 1440, { min: 1 })),
    portfolioNoveltyProfile: getNoveltyProfile(Bun.env.PORTFOLIO_NOVELTY_PROFILE),
    portfolioDiversityWeight: getEnvNumber('PORTFOLIO_DIVERSITY_WEIGHT', 1, { min: 0 }),
    optimizeExecutor: getOptimizeExecutor(Bun.env.OPTIMIZE_EXECUTOR),
    watchlist: watchlistRaw
      .split(',')
      .map((symbol) => symbol.trim().toUpperCase())
      .filter(Boolean),
    newsFeedSources,
  }
}
